"""
State schemas and data models for LangGraph agent orchestration.
Includes Pydantic models for structured outputs and TypedDict for LangGraph state passing.
"""

from typing import List, Dict, Any, Optional, Literal
from typing_extensions import TypedDict
from pydantic import BaseModel, Field


# -------------------------------------------------------------------------
# Pydantic Schemas for Structured Agent Outputs
# -------------------------------------------------------------------------

class SourceCitation(BaseModel):
    """Citation information for evidence collected during verification."""
    title: str = Field(description="Headline or title of the cited source")
    url: str = Field(description="URL of the evidence source")
    domain: str = Field(description="Domain name e.g. reuters.com")
    credibility_rating: int = Field(default=80, description="Domain credibility rating 0-100")
    snippet: str = Field(description="Relevant text excerpt supporting or refuting the claim")
    stance: Literal["supports", "refutes", "neutral", "context"] = Field(
        default="neutral", description="Stance of this evidence relative to the claim"
    )


class FactCheckVerdict(BaseModel):
    """Final structured verdict generated by the Fact-Checking Agent."""
    claim: str = Field(description="The original or clarified claim evaluated")
    verdict: Literal["TRUE", "LIKELY TRUE", "MIXTURE", "MISLEADING", "FALSE", "UNVERIFIED"] = Field(
        description="Standardized verdict classification"
    )
    credibility_score: float = Field(
        ge=0.0, le=100.0, description="Overall credibility score from 0 to 100"
    )
    confidence: float = Field(
        ge=0.0, le=100.0, description="Model confidence in verdict from 0 to 100"
    )
    summary: str = Field(description="Concise 1-2 sentence executive summary of the verdict")
    reasoning: str = Field(description="Detailed step-by-step reasoning synthesizing evidence")
    clickbait_score: float = Field(
        default=0.0, ge=0.0, le=100.0, description="Sensationalism / clickbait score"
    )
    clickbait_flags: List[str] = Field(
        default_factory=list, description="Specific clickbait traits identified"
    )
    is_safe: bool = Field(default=True, description="Safety guardrail pass status")
    safety_notes: Optional[str] = Field(default=None, description="Safety guardrail assessment")
    sources: List[SourceCitation] = Field(
        default_factory=list, description="List of source citations used"
    )
    react_steps: List[Dict[str, Any]] = Field(
        default_factory=list, description="ReAct loop trace thoughts and actions"
    )


class ArticleSummary(BaseModel):
    """Individual news article summarized for daily digest."""
    title: str
    category: str
    source: str
    url: str
    published: str
    summary: str
    key_points: List[str] = Field(default_factory=list)
    credibility_score: int = 85
    clickbait_score: float = 0.0


class NewsDigestResult(BaseModel):
    """Compiled news digest for a category or across categories."""
    date: str
    category: str
    total_articles: int
    executive_summary: str
    trending_topics: List[str] = Field(default_factory=list)
    articles: List[ArticleSummary] = Field(default_factory=list)
    markdown_content: str = ""


# -------------------------------------------------------------------------
# LangGraph State Schema (TypedDict)
# -------------------------------------------------------------------------

class FactCheckState(TypedDict, total=False):
    """State passed through the LangGraph fact-checking workflow."""
    # Inputs
    raw_claim: str
    cleaned_claim: str

    # Safety Guardrail State
    is_safe: bool
    safety_notes: str

    # Clickbait / Sensationalism Analysis
    clickbait_score: float
    clickbait_flags: List[str]

    # Retrieval States
    rag_evidence: List[Dict[str, Any]]
    web_evidence: List[Dict[str, Any]]

    # ReAct Deliberation Loop
    react_thoughts: List[Dict[str, str]]
    search_queries_run: List[str]
    iteration_count: int

    # Final Synthesis
    verdict: str
    credibility_score: float
    confidence: float
    summary: str
    reasoning: str
    sources: List[Dict[str, Any]]
    final_output: Optional[FactCheckVerdict]

    # Error handling
    error: Optional[str]


class NewsDigestState(TypedDict, total=False):
    """State passed through the LangGraph news digest workflow."""
    category: str
    limit: int
    raw_articles: List[Dict[str, Any]]
    filtered_articles: List[Dict[str, Any]]
    summarized_articles: List[Dict[str, Any]]
    executive_summary: str
    trending_topics: List[str]
    digest_markdown: str
    final_digest: Optional[NewsDigestResult]
    error: Optional[str]
